-- Aspidus Trade Management Platform — Complete Supabase Schema
-- Auto-generated from actual database state


CREATE TABLE IF NOT EXISTS api_keys (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  name text NOT NULL,
  key_prefix text NOT NULL,
  key_hash text NOT NULL,
  permissions jsonb NOT NULL DEFAULT '[]'::jsonb,
  last_used_at timestamptz,
  last_used_ip text,
  active boolean NOT NULL DEFAULT true,
  expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text,
  user_id text,
  username text,
  action text NOT NULL,
  entity_type text,
  entity_id text,
  details jsonb,
  ip text,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS commission_agents (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  partner_id text NOT NULL,
  commission_type text NOT NULL DEFAULT 'profit_percent'::text,
  commission_rate numeric NOT NULL DEFAULT 0,
  commission_per_unit numeric NOT NULL DEFAULT 0,
  commission_custom_formula text,
  commission_currency text NOT NULL DEFAULT 'RSD'::text,
  is_default boolean NOT NULL DEFAULT false,
  active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS commission_payouts (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  agent_id text NOT NULL,
  partner_id text NOT NULL,
  total_amount numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'RSD'::text,
  commission_ids ARRAY NOT NULL DEFAULT '{}'::text[],
  payment_method text,
  payment_reference text,
  paid_at timestamptz,
  status text NOT NULL DEFAULT 'pending'::text,
  notes text,
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS deal_commissions (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  deal_id text NOT NULL,
  agent_id text NOT NULL,
  partner_id text NOT NULL,
  commission_type text NOT NULL DEFAULT 'profit_percent'::text,
  commission_rate numeric NOT NULL DEFAULT 0,
  commission_per_unit numeric NOT NULL DEFAULT 0,
  commission_custom_formula text,
  commission_currency text NOT NULL DEFAULT 'RSD'::text,
  deal_value numeric NOT NULL DEFAULT 0,
  deal_profit numeric NOT NULL DEFAULT 0,
  deal_quantity numeric NOT NULL DEFAULT 0,
  deal_unit text NOT NULL DEFAULT ''::text,
  calculated_commission numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending'::text,
  approved_by text,
  approved_at timestamptz,
  paid_at timestamptz,
  payout_reference text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS deals (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  title text NOT NULL,
  partner_id text NOT NULL,
  owner_id text,
  stage text NOT NULL DEFAULT 'lead'::text,
  value numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'USD'::text,
  expected_close date,
  probability integer NOT NULL DEFAULT 0,
  description text,
  lost_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  commission_agent_id text,
  buy_cost numeric NOT NULL DEFAULT 0,
  quantity numeric NOT NULL DEFAULT 0,
  unit text NOT NULL DEFAULT ''::text,
  buyer_id text,
  supplier_id text,
  product_id text,
  contract_id text,
  incoterm text,
  delivery_date date,
  delivery_location text,
  exchange_rate double precision DEFAULT 1,
  purchase_price numeric,
  purchase_currency text,
  selling_price numeric,
  selling_currency text,
  bank_costs numeric DEFAULT 0,
  supplier_bank_details text,
  payment_account_id text,
  payment_dates jsonb,
  associates jsonb,
  costs jsonb,
  documents jsonb,
  buyer_paid_on text,
  supplier_paid_on text,
  old_id text
);

CREATE TABLE IF NOT EXISTS demands (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  number text NOT NULL,
  partner_id text NOT NULL,
  status text NOT NULL DEFAULT 'open'::text,
  subject text NOT NULL,
  description text,
  requested_delivery date,
  currency text NOT NULL DEFAULT 'USD'::text,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  buyer_id text,
  product_id text,
  product_name text,
  target_price numeric,
  is_new_product boolean DEFAULT false,
  source text,
  auto_hints jsonb,
  old_id text,
  buyer_bank text,
  destination text,
  needed_by date,
  payment_terms text,
  logistics_agent text,
  logistics_agent_contact text,
  end_buyer text,
  requestor text,
  priority text NOT NULL DEFAULT 'medium'::text
);

CREATE TABLE IF NOT EXISTS document_register (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  number text NOT NULL,
  type text NOT NULL DEFAULT 'other'::text,
  version integer NOT NULL DEFAULT 1,
  reference_id text,
  partner_id text,
  title text NOT NULL,
  status text NOT NULL DEFAULT 'current'::text,
  created_by text,
  metadata jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS document_revisions (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  document_id text NOT NULL,
  version integer NOT NULL,
  change_note text NOT NULL DEFAULT ''::text,
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS document_templates (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  name text NOT NULL,
  type text NOT NULL DEFAULT 'generic'::text,
  is_default boolean NOT NULL DEFAULT false,
  page_size text NOT NULL DEFAULT 'A4'::text,
  page_margin_top numeric NOT NULL DEFAULT 25,
  page_margin_bottom numeric NOT NULL DEFAULT 25,
  page_margin_left numeric NOT NULL DEFAULT 20,
  page_margin_right numeric NOT NULL DEFAULT 20,
  header_enabled boolean NOT NULL DEFAULT true,
  header_height numeric NOT NULL DEFAULT 20,
  header_content text,
  header_show_logo boolean NOT NULL DEFAULT true,
  header_show_company_name boolean NOT NULL DEFAULT true,
  header_show_contact boolean NOT NULL DEFAULT true,
  footer_enabled boolean NOT NULL DEFAULT true,
  footer_height numeric NOT NULL DEFAULT 15,
  footer_content text,
  footer_show_page_number boolean NOT NULL DEFAULT true,
  footer_show_bank_details boolean NOT NULL DEFAULT true,
  footer_show_tax_id boolean NOT NULL DEFAULT true,
  body_font_family text NOT NULL DEFAULT 'Inter'::text,
  body_font_size numeric NOT NULL DEFAULT 11,
  body_line_height numeric NOT NULL DEFAULT 1.5,
  primary_color text NOT NULL DEFAULT '#0f766e'::text,
  accent_color text NOT NULL DEFAULT '#0d9488'::text,
  table_header_bg text NOT NULL DEFAULT '#0f766e'::text,
  table_header_color text NOT NULL DEFAULT '#ffffff'::text,
  table_border_color text NOT NULL DEFAULT '#e5e7eb'::text,
  table_stripe boolean NOT NULL DEFAULT true,
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS document_verifications (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  document_type text NOT NULL,
  document_id text NOT NULL,
  document_number text NOT NULL,
  verification_code text NOT NULL,
  pdf_hash text NOT NULL,
  pdf_size bigint NOT NULL DEFAULT 0,
  issued_to_partner_id text,
  issued_at timestamptz NOT NULL DEFAULT now(),
  verification_count integer NOT NULL DEFAULT 0,
  last_verified_at timestamptz,
  last_verified_ip text,
  status text NOT NULL DEFAULT 'active'::text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS entity_notes (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  content text NOT NULL,
  pinned boolean NOT NULL DEFAULT false,
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS erp_accounts (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  code text NOT NULL,
  name text NOT NULL,
  name_en text,
  account_type text NOT NULL,
  account_category text,
  parent_id text,
  is_active boolean NOT NULL DEFAULT true,
  is_system boolean NOT NULL DEFAULT false,
  standard text,
  tax_code text,
  description text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS erp_bank_accounts (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  account_id text NOT NULL,
  bank_name text NOT NULL,
  account_number text NOT NULL,
  iban text,
  swift_bic text,
  currency text NOT NULL DEFAULT 'EUR'::text,
  balance double precision NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  old_id text,
  linked_company_bank_idx integer
);

CREATE TABLE IF NOT EXISTS erp_bank_transactions (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  bank_account_id text NOT NULL,
  date timestamptz NOT NULL,
  amount double precision NOT NULL,
  transaction_type text NOT NULL,
  description text,
  reference text,
  counterparty text,
  counterparty_account text,
  is_reconciled boolean NOT NULL DEFAULT false,
  reconciled_with text,
  journal_entry_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  old_id text,
  deal_id text,
  invoice_number text,
  category text,
  is_auto_generated boolean DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS erp_cost_centers (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  code text NOT NULL,
  name text NOT NULL,
  parent_id text,
  is_active boolean NOT NULL DEFAULT true,
  description text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS erp_journal_entries (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  entry_number text NOT NULL,
  date timestamptz NOT NULL,
  description text NOT NULL,
  reference_type text,
  reference_id text,
  fiscal_period_id text,
  status text NOT NULL DEFAULT 'draft'::text,
  source_type text,
  debit_total double precision NOT NULL DEFAULT 0,
  credit_total double precision NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'EUR'::text,
  exchange_rate double precision NOT NULL DEFAULT 1,
  notes text,
  created_by text NOT NULL,
  posted_by text,
  posted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS erp_journal_lines (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  journal_entry_id text NOT NULL,
  account_id text NOT NULL,
  line_number integer NOT NULL,
  description text,
  debit double precision NOT NULL DEFAULT 0,
  credit double precision NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'EUR'::text,
  partner_id text,
  cost_center_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  tenant_id text NOT NULL
);

CREATE TABLE IF NOT EXISTS erp_settings (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  accounting_standard text NOT NULL DEFAULT 'eu'::text,
  fiscal_year_start text NOT NULL DEFAULT '01-01'::text,
  fiscal_year_end text NOT NULL DEFAULT '12-31'::text,
  default_currency text NOT NULL DEFAULT 'EUR'::text,
  vat_enabled boolean NOT NULL DEFAULT true,
  vat_rate double precision NOT NULL DEFAULT 20,
  vat_return_period text NOT NULL DEFAULT 'quarterly'::text,
  auto_post_journal boolean NOT NULL DEFAULT false,
  revenue_account_id text,
  expense_account_id text,
  receivable_account_id text,
  payable_account_id text,
  vat_account_id text,
  bank_charges_account_id text,
  cash_account_id text,
  retention_account_id text,
  round_off_account_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS feature_flags (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  module_crm boolean NOT NULL DEFAULT true,
  module_trade boolean NOT NULL DEFAULT true,
  module_finance boolean NOT NULL DEFAULT true,
  module_inventory boolean NOT NULL DEFAULT true,
  module_portal boolean NOT NULL DEFAULT true,
  module_kyc boolean NOT NULL DEFAULT true,
  module_document_templates boolean NOT NULL DEFAULT true,
  module_document_verification boolean NOT NULL DEFAULT true,
  module_vault boolean NOT NULL DEFAULT true,
  module_api_keys boolean NOT NULL DEFAULT true,
  module_webhooks boolean NOT NULL DEFAULT true,
  module_mail_queue boolean NOT NULL DEFAULT true,
  module_security boolean NOT NULL DEFAULT true,
  max_partners integer NOT NULL DEFAULT 0,
  max_users integer NOT NULL DEFAULT 25,
  max_monthly_documents integer NOT NULL DEFAULT 0,
  beta_ai_assistant boolean NOT NULL DEFAULT false,
  beta_advanced_analytics boolean NOT NULL DEFAULT false,
  updated_by text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS fiscal_periods (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  name text NOT NULL,
  start_date timestamptz NOT NULL,
  end_date timestamptz NOT NULL,
  period_type text NOT NULL DEFAULT 'monthly'::text,
  status text NOT NULL DEFAULT 'open'::text,
  fiscal_year integer NOT NULL,
  closed_by text,
  closed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS inventory_movements (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  partner_id text NOT NULL,
  product_id text NOT NULL,
  delta numeric NOT NULL DEFAULT 0,
  reason text NOT NULL,
  reference text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS invoices (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  number text NOT NULL,
  offer_id text,
  partner_id text NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text,
  subject text NOT NULL,
  currency text NOT NULL DEFAULT 'USD'::text,
  subtotal numeric NOT NULL DEFAULT 0,
  discount_total numeric NOT NULL DEFAULT 0,
  tax_total numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  issue_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date NOT NULL DEFAULT (CURRENT_DATE + 14),
  sent_at timestamptz,
  paid_at timestamptz,
  notes text,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  payment_terms text
);

CREATE TABLE IF NOT EXISTS known_ips (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  user_id text NOT NULL,
  ip text NOT NULL,
  country text,
  first_seen timestamptz NOT NULL DEFAULT now(),
  last_seen timestamptz NOT NULL DEFAULT now(),
  trusted boolean NOT NULL DEFAULT false,
  tenant_id text NOT NULL
);

CREATE TABLE IF NOT EXISTS kyc_submissions (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  partner_id text NOT NULL,
  portal_access_id text,
  status text NOT NULL DEFAULT 'draft'::text,
  entity_type text NOT NULL DEFAULT 'company'::text,
  legal_name text,
  trade_name text,
  registration_number text,
  tax_id text,
  vat_number text,
  company_website text,
  address_line text,
  city text,
  state text,
  postal_code text,
  country text,
  contact_name text,
  contact_email text,
  contact_phone text,
  contact_position text,
  owner_name text,
  owner_id_type text,
  owner_id_number text,
  owner_nationality text,
  owner_dob date,
  owner_address text,
  business_activity text,
  expected_monthly_volume text,
  source_of_funds text,
  bank_name text,
  bank_account text,
  bank_iban text,
  bank_swift text,
  documents jsonb NOT NULL DEFAULT '[]'::jsonb,
  reviewed_by text,
  reviewed_at timestamptz,
  review_notes text,
  rejection_reason text,
  auto_transferred boolean NOT NULL DEFAULT false,
  submitted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS login_history (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text,
  user_id text,
  username text,
  ip text,
  user_agent text,
  country text,
  success boolean NOT NULL DEFAULT false,
  reason text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS mail_queue (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text,
  to_email text NOT NULL,
  subject text NOT NULL,
  body text NOT NULL DEFAULT ''::text,
  status text NOT NULL DEFAULT 'queued'::text,
  attempts integer NOT NULL DEFAULT 0,
  error text,
  sent_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS notifications (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  user_id text,
  type text NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  entity_type text,
  entity_id text,
  read boolean NOT NULL DEFAULT false,
  read_at timestamptz,
  action_url text,
  action_label text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS offers (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  number text NOT NULL,
  deal_id text,
  partner_id text NOT NULL,
  owner_id text,
  status text NOT NULL DEFAULT 'draft'::text,
  subject text NOT NULL,
  currency text NOT NULL DEFAULT 'USD'::text,
  subtotal numeric NOT NULL DEFAULT 0,
  discount_total numeric NOT NULL DEFAULT 0,
  tax_total numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  notes text,
  terms text,
  valid_until date,
  sent_at timestamptz,
  responded_at timestamptz,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  offer_no text,
  bank_details text,
  pol text,
  pod text,
  vessel text,
  container_no text,
  lead_time text,
  packaging text,
  payment_terms text,
  tax_clause text,
  document_id text,
  pdf_file_url text,
  pdf_generated_at timestamptz,
  selling_price numeric,
  quantity numeric,
  unit text,
  product_id text,
  incoterm text,
  services jsonb,
  payment_bank_idx integer,
  client_accepted_at timestamptz,
  client_signature jsonb,
  client_note text,
  admin_reviewed_by_client boolean DEFAULT false,
  old_id text
);

CREATE TABLE IF NOT EXISTS partner_connections (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  source_id text NOT NULL,
  target_id text NOT NULL,
  relation_type text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS partners (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  name text NOT NULL,
  entity_type text NOT NULL DEFAULT 'company'::text,
  type text NOT NULL DEFAULT 'buyer'::text,
  email text,
  phone text,
  website text,
  tax_id text,
  vat_number text,
  registration_number text,
  address_line text,
  city text,
  state text,
  postal_code text,
  country text,
  contact_name text,
  contact_email text,
  contact_phone text,
  bank_name text,
  bank_account text,
  bank_swift text,
  bank_iban text,
  preferred_currency text,
  preferred_incoterm text,
  preferred_payment_terms text,
  status text NOT NULL DEFAULT 'active'::text,
  risk_score integer NOT NULL DEFAULT 0,
  notes text,
  tags ARRAY,
  portal_enabled boolean NOT NULL DEFAULT false,
  portal_token text,
  portal_level text NOT NULL DEFAULT 'none'::text,
  kyc_status text NOT NULL DEFAULT 'not_submitted'::text,
  kyc_data jsonb,
  kyc_reviewed_by text,
  kyc_reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  is_commissioner boolean NOT NULL DEFAULT false,
  whatsapp text,
  lead_source text,
  rating integer NOT NULL DEFAULT 0,
  portal_visible_products ARRAY,
  portal_permissions ARRAY,
  linked_company_id text,
  industry text,
  social jsonb,
  activities jsonb,
  old_id text
);

CREATE TABLE IF NOT EXISTS portal_access (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  partner_id text NOT NULL,
  tenant_id text NOT NULL,
  tier text NOT NULL DEFAULT 'standard'::text,
  can_view_offers boolean NOT NULL DEFAULT true,
  can_view_documents boolean NOT NULL DEFAULT true,
  can_view_catalog boolean NOT NULL DEFAULT true,
  can_view_invoices boolean NOT NULL DEFAULT false,
  can_view_profile boolean NOT NULL DEFAULT true,
  can_view_company_info boolean NOT NULL DEFAULT true,
  can_submit_rfq boolean NOT NULL DEFAULT true,
  can_download_pdf boolean NOT NULL DEFAULT true,
  exempt_kyc boolean NOT NULL DEFAULT false,
  exempt_document_upload boolean NOT NULL DEFAULT false,
  exempt_location_share boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'pending_approval'::text,
  approved_by text,
  approved_at timestamptz,
  invited_at timestamptz,
  welcome_email_sent boolean NOT NULL DEFAULT false,
  portal_email text,
  password_hash text,
  must_set_password boolean NOT NULL DEFAULT true,
  last_login_at timestamptz,
  last_login_ip text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  failed_attempts integer NOT NULL DEFAULT 0,
  locked_until timestamptz,
  token_version integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS portal_rfqs (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  partner_id text NOT NULL,
  portal_access_id text,
  number text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  product_name text NOT NULL,
  product_description text,
  category text,
  quantity numeric NOT NULL DEFAULT 0,
  unit text NOT NULL DEFAULT 'MT'::text,
  target_price numeric,
  currency text NOT NULL DEFAULT 'USD'::text,
  delivery_country text,
  delivery_port text,
  delivery_date date,
  incoterm text,
  specifications text,
  notes text,
  linked_offer_id text,
  linked_demand_id text,
  admin_notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deal_id text
);

CREATE TABLE IF NOT EXISTS product_catalog (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  name text NOT NULL,
  category text NOT NULL DEFAULT 'OTHER'::text,
  hs_code text,
  description text,
  base_unit text NOT NULL DEFAULT 'MT'::text,
  specifications jsonb,
  origin_country text,
  images ARRAY,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  old_id text,
  brand text,
  shelf_life text,
  image_url text,
  logistics jsonb,
  coa_params jsonb,
  detailed_spec text,
  tags ARRAY,
  inventory jsonb,
  sku text
);

CREATE TABLE IF NOT EXISTS products (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  sku text NOT NULL,
  name text NOT NULL,
  description text,
  category text,
  unit text NOT NULL DEFAULT 'pcs'::text,
  price numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'USD'::text,
  cost numeric,
  stock numeric NOT NULL DEFAULT 0,
  reorder_level numeric NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  attributes jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  hs_code text,
  brand text,
  shelf_life text,
  image_url text,
  logistics jsonb,
  coa_params jsonb,
  detailed_spec text,
  tags ARRAY,
  old_id text,
  inventory jsonb
);

CREATE TABLE IF NOT EXISTS proformas (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  number text NOT NULL,
  offer_id text,
  partner_id text NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text,
  subject text NOT NULL,
  currency text NOT NULL DEFAULT 'USD'::text,
  subtotal numeric NOT NULL DEFAULT 0,
  discount_total numeric NOT NULL DEFAULT 0,
  tax_total numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  issue_date date NOT NULL DEFAULT CURRENT_DATE,
  valid_until date NOT NULL DEFAULT (CURRENT_DATE + 14),
  sent_at timestamptz,
  paid_at timestamptz,
  notes text,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  payment_terms text
);

CREATE TABLE IF NOT EXISTS recurring_expenses (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  account_id text NOT NULL,
  description text NOT NULL,
  category text,
  amount double precision NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'USD'::text,
  day_of_month integer NOT NULL DEFAULT 1,
  start_date date,
  last_applied date,
  is_active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sessions (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  user_id text NOT NULL,
  token text NOT NULL,
  ip text,
  user_agent text,
  country text,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_used_at timestamptz,
  expires_at timestamptz NOT NULL,
  revoked boolean NOT NULL DEFAULT false,
  current boolean NOT NULL DEFAULT false,
  tenant_id text NOT NULL
);

CREATE TABLE IF NOT EXISTS settings (
  key text NOT NULL,
  tenant_id text,
  value jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS shared_documents (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  partner_id text NOT NULL,
  filename text NOT NULL,
  mime_type text NOT NULL DEFAULT 'application/octet-stream'::text,
  size bigint NOT NULL DEFAULT 0,
  storage_path text NOT NULL,
  category text NOT NULL DEFAULT 'other'::text,
  uploaded_by text,
  visible_to_partner boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS supplier_offers (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  product_id text NOT NULL,
  supplier_id text NOT NULL,
  offer_number text,
  status text NOT NULL DEFAULT 'active'::text,
  unit_price numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'USD'::text,
  min_order_qty numeric,
  price_valid_until date,
  packaging text,
  packing_details text,
  loadability text,
  specification_notes text,
  origin_country text,
  incoterm text NOT NULL DEFAULT 'FOB'::text,
  loading_port text,
  delivery_port text,
  lead_time_days integer,
  payment_terms text,
  inspection text,
  certificate text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tenants (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  name text NOT NULL,
  legal_name text,
  country text,
  currency text NOT NULL DEFAULT 'USD'::text,
  tax_id text,
  vat_number text,
  registration_number text,
  address_line text,
  city text,
  postal_code text,
  bank_name text,
  bank_iban text,
  bank_swift text,
  logo_url text,
  primary_color text,
  plan text NOT NULL DEFAULT 'trial'::text,
  status text NOT NULL DEFAULT 'active'::text,
  max_users integer NOT NULL DEFAULT 10,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  website text,
  phone text,
  email text,
  bank_accounts jsonb
);

CREATE TABLE IF NOT EXISTS trade_calculations (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  name text NOT NULL,
  product_id text,
  supplier_offer_id text,
  supplier_id text,
  buyer_id text,
  quantity numeric NOT NULL DEFAULT 0,
  unit text NOT NULL DEFAULT 'MT'::text,
  num_containers integer NOT NULL DEFAULT 1,
  container_type text,
  buy_price_per_unit numeric NOT NULL DEFAULT 0,
  buy_currency text NOT NULL DEFAULT 'USD'::text,
  buy_incoterm text NOT NULL DEFAULT 'FOB'::text,
  sell_price_per_unit numeric NOT NULL DEFAULT 0,
  sell_currency text NOT NULL DEFAULT 'USD'::text,
  sell_incoterm text NOT NULL DEFAULT 'CIF'::text,
  transport_mode text NOT NULL DEFAULT 'SEA'::text,
  loading_port text,
  delivery_port text,
  exchange_rate numeric NOT NULL DEFAULT 1,
  cost_lines jsonb NOT NULL DEFAULT '[]'::jsonb,
  total_buy_cost numeric NOT NULL DEFAULT 0,
  total_landed_cost numeric NOT NULL DEFAULT 0,
  total_sell_revenue numeric NOT NULL DEFAULT 0,
  gross_margin numeric NOT NULL DEFAULT 0,
  margin_percent numeric NOT NULL DEFAULT 0,
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS trusted_devices (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  user_id text NOT NULL,
  device_name text NOT NULL,
  fingerprint text NOT NULL,
  ip text,
  last_used timestamptz NOT NULL DEFAULT now(),
  revoked boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  tenant_id text NOT NULL
);

CREATE TABLE IF NOT EXISTS user_preferences (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  user_id text NOT NULL,
  preference_key text NOT NULL,
  preference_value text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_tasks (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  user_id text NOT NULL,
  title text NOT NULL,
  done boolean NOT NULL DEFAULT false,
  due_date date,
  entity_type text,
  entity_id text,
  priority text NOT NULL DEFAULT 'medium'::text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text,
  username text NOT NULL,
  email text NOT NULL,
  full_name text,
  role text NOT NULL DEFAULT 'staff'::text,
  permissions jsonb,
  password_hash text NOT NULL,
  totp_secret text,
  totp_enabled boolean NOT NULL DEFAULT false,
  locked_until timestamptz,
  failed_attempts integer NOT NULL DEFAULT 0,
  last_login_at timestamptz,
  last_login_ip text,
  last_login_country text,
  must_change_password boolean NOT NULL DEFAULT false,
  token_version integer NOT NULL DEFAULT 1,
  signature text,
  notif_prefs jsonb,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vault_secrets (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  key text NOT NULL,
  description text,
  encrypted_value text NOT NULL,
  category text NOT NULL DEFAULT 'other'::text,
  last_accessed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS verification_logs (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  verification_id text NOT NULL,
  code text NOT NULL,
  ip text,
  user_agent text,
  result text NOT NULL,
  details jsonb,
  verified_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS webhooks (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  tenant_id text NOT NULL,
  name text NOT NULL,
  url text NOT NULL,
  events jsonb NOT NULL DEFAULT '[]'::jsonb,
  secret text NOT NULL,
  last_triggered_at timestamptz,
  last_status integer,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

