-- Aspidus Supabase Schema (auto-generated from live DB)
-- Generated: 2026-08-06
-- Source: live production DB via Supabase Management API

CREATE TABLE IF NOT EXISTS api_keys (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  name text NOT NULL,
  key_prefix text NOT NULL,
  key_hash text NOT NULL,
  permissions jsonb DEFAULT '[]'::jsonb NOT NULL,
  last_used_at timestamp with time zone,
  last_used_ip text,
  active boolean DEFAULT true NOT NULL,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text,
  user_id text,
  username text,
  action text NOT NULL,
  entity_type text,
  entity_id text,
  details jsonb,
  ip text,
  user_agent text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS commission_agents (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  partner_id text NOT NULL,
  commission_type text DEFAULT 'profit_percent'::text NOT NULL,
  commission_rate numeric DEFAULT 0 NOT NULL,
  commission_per_unit numeric DEFAULT 0 NOT NULL,
  commission_custom_formula text,
  commission_currency text DEFAULT 'RSD'::text NOT NULL,
  is_default boolean DEFAULT false NOT NULL,
  active boolean DEFAULT true NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS commission_payouts (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  agent_id text NOT NULL,
  partner_id text NOT NULL,
  total_amount numeric DEFAULT 0 NOT NULL,
  currency text DEFAULT 'RSD'::text NOT NULL,
  commission_ids ARRAY DEFAULT '{}'::text[] NOT NULL,
  payment_method text,
  payment_reference text,
  paid_at timestamp with time zone,
  status text DEFAULT 'pending'::text NOT NULL,
  notes text,
  created_by text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS deal_commissions (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  deal_id text NOT NULL,
  agent_id text NOT NULL,
  partner_id text NOT NULL,
  commission_type text DEFAULT 'profit_percent'::text NOT NULL,
  commission_rate numeric DEFAULT 0 NOT NULL,
  commission_per_unit numeric DEFAULT 0 NOT NULL,
  commission_custom_formula text,
  commission_currency text DEFAULT 'RSD'::text NOT NULL,
  deal_value numeric DEFAULT 0 NOT NULL,
  deal_profit numeric DEFAULT 0 NOT NULL,
  deal_quantity numeric DEFAULT 0 NOT NULL,
  deal_unit text DEFAULT ''::text NOT NULL,
  calculated_commission numeric DEFAULT 0 NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  approved_by text,
  approved_at timestamp with time zone,
  paid_at timestamp with time zone,
  payout_reference text,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS deals (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  title text NOT NULL,
  partner_id text NOT NULL,
  owner_id text,
  stage text DEFAULT 'lead'::text NOT NULL,
  value numeric DEFAULT 0 NOT NULL,
  currency text DEFAULT 'USD'::text NOT NULL,
  expected_close date,
  probability integer DEFAULT 0 NOT NULL,
  description text,
  lost_reason text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  commission_agent_id text,
  buy_cost numeric DEFAULT 0 NOT NULL,
  quantity numeric DEFAULT 0 NOT NULL,
  unit text DEFAULT ''::text NOT NULL,
  buyer_id text,
  supplier_id text,
  product_id text,
  contract_id text,
  incoterm text,
  delivery_date date,
  delivery_location text,
  exchange_rate double precision DEFAULT 1,
  purchase_price numeric,
  purchase_currency text,
  selling_price numeric,
  selling_currency text,
  bank_costs numeric DEFAULT 0,
  supplier_bank_details text,
  payment_account_id text,
  payment_dates jsonb,
  associates jsonb,
  costs jsonb,
  documents jsonb,
  buyer_paid_on text,
  supplier_paid_on text,
  old_id text
);

CREATE TABLE IF NOT EXISTS demands (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  number text NOT NULL,
  partner_id text NOT NULL,
  status text DEFAULT 'open'::text NOT NULL,
  subject text NOT NULL,
  description text,
  requested_delivery date,
  currency text DEFAULT 'USD'::text NOT NULL,
  items jsonb DEFAULT '[]'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  buyer_id text,
  product_id text,
  product_name text,
  target_price numeric,
  is_new_product boolean DEFAULT false,
  source text,
  auto_hints jsonb,
  old_id text,
  buyer_bank text,
  destination text,
  needed_by date,
  payment_terms text,
  logistics_agent text,
  logistics_agent_contact text,
  end_buyer text,
  requestor text,
  priority text DEFAULT 'medium'::text NOT NULL
);

CREATE TABLE IF NOT EXISTS document_register (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  number text NOT NULL,
  type text DEFAULT 'other'::text NOT NULL,
  version integer DEFAULT 1 NOT NULL,
  reference_id text,
  partner_id text,
  title text NOT NULL,
  status text DEFAULT 'current'::text NOT NULL,
  created_by text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS document_revisions (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  document_id text NOT NULL,
  version integer NOT NULL,
  change_note text DEFAULT ''::text NOT NULL,
  created_by text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  document_type text,
  changed_fields jsonb,
  snapshot_before jsonb,
  changed_by_username text
);

CREATE TABLE IF NOT EXISTS document_sequences (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  doc_type text NOT NULL,
  year integer NOT NULL,
  last_number integer DEFAULT 0 NOT NULL,
  prefix text DEFAULT ''::text NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS document_templates (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  name text NOT NULL,
  type text DEFAULT 'generic'::text NOT NULL,
  is_default boolean DEFAULT false NOT NULL,
  page_size text DEFAULT 'A4'::text NOT NULL,
  page_margin_top numeric DEFAULT 25 NOT NULL,
  page_margin_bottom numeric DEFAULT 25 NOT NULL,
  page_margin_left numeric DEFAULT 20 NOT NULL,
  page_margin_right numeric DEFAULT 20 NOT NULL,
  header_enabled boolean DEFAULT true NOT NULL,
  header_height numeric DEFAULT 20 NOT NULL,
  header_content text,
  header_show_logo boolean DEFAULT true NOT NULL,
  header_show_company_name boolean DEFAULT true NOT NULL,
  header_show_contact boolean DEFAULT true NOT NULL,
  footer_enabled boolean DEFAULT true NOT NULL,
  footer_height numeric DEFAULT 15 NOT NULL,
  footer_content text,
  footer_show_page_number boolean DEFAULT true NOT NULL,
  footer_show_bank_details boolean DEFAULT true NOT NULL,
  footer_show_tax_id boolean DEFAULT true NOT NULL,
  body_font_family text DEFAULT 'Inter'::text NOT NULL,
  body_font_size numeric DEFAULT 11 NOT NULL,
  body_line_height numeric DEFAULT 1.5 NOT NULL,
  primary_color text DEFAULT '#0f766e'::text NOT NULL,
  accent_color text DEFAULT '#0d9488'::text NOT NULL,
  table_header_bg text DEFAULT '#0f766e'::text NOT NULL,
  table_header_color text DEFAULT '#ffffff'::text NOT NULL,
  table_border_color text DEFAULT '#e5e7eb'::text NOT NULL,
  table_stripe boolean DEFAULT true NOT NULL,
  created_by text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  letterhead_id text,
  seal_id text,
  seal_enabled boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS document_verifications (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  document_type text NOT NULL,
  document_id text NOT NULL,
  document_number text NOT NULL,
  verification_code text NOT NULL,
  pdf_hash text NOT NULL,
  pdf_size bigint DEFAULT 0 NOT NULL,
  issued_to_partner_id text,
  issued_at timestamp with time zone DEFAULT now() NOT NULL,
  verification_count integer DEFAULT 0 NOT NULL,
  last_verified_at timestamp with time zone,
  last_verified_ip text,
  status text DEFAULT 'active'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS entity_notes (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  content text NOT NULL,
  pinned boolean DEFAULT false NOT NULL,
  created_by text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS erp_accounts (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  code text NOT NULL,
  name text NOT NULL,
  name_en text,
  account_type text NOT NULL,
  account_category text,
  parent_id text,
  is_active boolean DEFAULT true NOT NULL,
  is_system boolean DEFAULT false NOT NULL,
  standard text,
  tax_code text,
  description text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS erp_bank_accounts (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  account_id text NOT NULL,
  bank_name text NOT NULL,
  account_number text NOT NULL,
  iban text,
  swift_bic text,
  currency text DEFAULT 'EUR'::text NOT NULL,
  balance double precision DEFAULT 0 NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  old_id text,
  linked_company_bank_idx integer
);

CREATE TABLE IF NOT EXISTS erp_bank_transactions (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  bank_account_id text NOT NULL,
  date timestamp with time zone NOT NULL,
  amount double precision NOT NULL,
  transaction_type text NOT NULL,
  description text,
  reference text,
  counterparty text,
  counterparty_account text,
  is_reconciled boolean DEFAULT false NOT NULL,
  reconciled_with text,
  journal_entry_id text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  old_id text,
  deal_id text,
  invoice_number text,
  category text,
  is_auto_generated boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS erp_cost_centers (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  code text NOT NULL,
  name text NOT NULL,
  parent_id text,
  is_active boolean DEFAULT true NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS erp_journal_entries (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  entry_number text NOT NULL,
  date timestamp with time zone NOT NULL,
  description text NOT NULL,
  reference_type text,
  reference_id text,
  fiscal_period_id text,
  status text DEFAULT 'draft'::text NOT NULL,
  source_type text,
  debit_total double precision DEFAULT 0 NOT NULL,
  credit_total double precision DEFAULT 0 NOT NULL,
  currency text DEFAULT 'EUR'::text NOT NULL,
  exchange_rate double precision DEFAULT 1 NOT NULL,
  notes text,
  created_by text NOT NULL,
  posted_by text,
  posted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS erp_journal_lines (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  journal_entry_id text NOT NULL,
  account_id text NOT NULL,
  line_number integer NOT NULL,
  description text,
  debit double precision DEFAULT 0 NOT NULL,
  credit double precision DEFAULT 0 NOT NULL,
  currency text DEFAULT 'EUR'::text NOT NULL,
  partner_id text,
  cost_center_id text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  tenant_id text NOT NULL
);

CREATE TABLE IF NOT EXISTS erp_settings (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  accounting_standard text DEFAULT 'eu'::text NOT NULL,
  fiscal_year_start text DEFAULT '01-01'::text NOT NULL,
  fiscal_year_end text DEFAULT '12-31'::text NOT NULL,
  default_currency text DEFAULT 'EUR'::text NOT NULL,
  vat_enabled boolean DEFAULT true NOT NULL,
  vat_rate double precision DEFAULT 20 NOT NULL,
  vat_return_period text DEFAULT 'quarterly'::text NOT NULL,
  auto_post_journal boolean DEFAULT false NOT NULL,
  revenue_account_id text,
  expense_account_id text,
  receivable_account_id text,
  payable_account_id text,
  vat_account_id text,
  bank_charges_account_id text,
  cash_account_id text,
  retention_account_id text,
  round_off_account_id text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS expense_entries (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  user_id text NOT NULL,
  category text NOT NULL,
  description text,
  amount double precision NOT NULL,
  currency text DEFAULT 'EUR'::text,
  expense_date date NOT NULL,
  receipt_url text,
  status text DEFAULT 'pending'::text,
  approved_by text,
  approved_at timestamp with time zone,
  partner_id text,
  deal_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS feature_flags (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  module_crm boolean DEFAULT true NOT NULL,
  module_trade boolean DEFAULT true NOT NULL,
  module_finance boolean DEFAULT true NOT NULL,
  module_inventory boolean DEFAULT true NOT NULL,
  module_portal boolean DEFAULT true NOT NULL,
  module_kyc boolean DEFAULT true NOT NULL,
  module_document_templates boolean DEFAULT true NOT NULL,
  module_document_verification boolean DEFAULT true NOT NULL,
  module_vault boolean DEFAULT true NOT NULL,
  module_api_keys boolean DEFAULT true NOT NULL,
  module_webhooks boolean DEFAULT true NOT NULL,
  module_mail_queue boolean DEFAULT true NOT NULL,
  module_security boolean DEFAULT true NOT NULL,
  max_partners integer DEFAULT 0 NOT NULL,
  max_users integer DEFAULT 25 NOT NULL,
  max_monthly_documents integer DEFAULT 0 NOT NULL,
  beta_ai_assistant boolean DEFAULT false NOT NULL,
  beta_advanced_analytics boolean DEFAULT false NOT NULL,
  updated_by text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  module_logistics boolean DEFAULT true NOT NULL
);

CREATE TABLE IF NOT EXISTS file_manager (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  user_id text NOT NULL,
  folder text DEFAULT 'root'::text,
  filename text NOT NULL,
  file_url text,
  file_type text,
  file_size bigint DEFAULT 0,
  description text,
  tags text,
  shared_with text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS fiscal_periods (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  name text NOT NULL,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  period_type text DEFAULT 'monthly'::text NOT NULL,
  status text DEFAULT 'open'::text NOT NULL,
  fiscal_year integer NOT NULL,
  closed_by text,
  closed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_movements (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  partner_id text NOT NULL,
  product_id text NOT NULL,
  delta numeric DEFAULT 0 NOT NULL,
  reason text NOT NULL,
  reference text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS invoices (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  number text NOT NULL,
  offer_id text,
  partner_id text NOT NULL,
  status text DEFAULT 'draft'::text NOT NULL,
  subject text NOT NULL,
  currency text DEFAULT 'USD'::text NOT NULL,
  subtotal numeric DEFAULT 0 NOT NULL,
  discount_total numeric DEFAULT 0 NOT NULL,
  tax_total numeric DEFAULT 0 NOT NULL,
  total numeric DEFAULT 0 NOT NULL,
  issue_date date DEFAULT CURRENT_DATE NOT NULL,
  due_date date DEFAULT (CURRENT_DATE + 14) NOT NULL,
  sent_at timestamp with time zone,
  paid_at timestamp with time zone,
  notes text,
  items jsonb DEFAULT '[]'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  payment_terms text,
  deleted_at timestamp with time zone,
  incoterm text,
  pol text,
  pol_country text,
  pod text,
  pod_country text,
  vessel text,
  container_no text,
  lead_time text,
  packaging text,
  delivery_address text,
  delivery_city text,
  delivery_country text,
  specification text,
  origin_country text,
  exchange_rate double precision,
  exchange_rate_date text,
  exchange_rate_note text,
  viewed_at timestamp with time zone,
  viewed_by_email text,
  view_count integer DEFAULT 0,
  version integer DEFAULT 1
);

CREATE TABLE IF NOT EXISTS known_ips (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  user_id text NOT NULL,
  ip text NOT NULL,
  country text,
  first_seen timestamp with time zone DEFAULT now() NOT NULL,
  last_seen timestamp with time zone DEFAULT now() NOT NULL,
  trusted boolean DEFAULT false NOT NULL,
  tenant_id text NOT NULL
);

CREATE TABLE IF NOT EXISTS kyc_submissions (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  partner_id text NOT NULL,
  portal_access_id text,
  status text DEFAULT 'draft'::text NOT NULL,
  entity_type text DEFAULT 'company'::text NOT NULL,
  legal_name text,
  trade_name text,
  registration_number text,
  tax_id text,
  vat_number text,
  company_website text,
  address_line text,
  city text,
  state text,
  postal_code text,
  country text,
  contact_name text,
  contact_email text,
  contact_phone text,
  contact_position text,
  owner_name text,
  owner_id_type text,
  owner_id_number text,
  owner_nationality text,
  owner_dob date,
  owner_address text,
  business_activity text,
  expected_monthly_volume text,
  source_of_funds text,
  bank_name text,
  bank_account text,
  bank_iban text,
  bank_swift text,
  documents jsonb DEFAULT '[]'::jsonb NOT NULL,
  reviewed_by text,
  reviewed_at timestamp with time zone,
  review_notes text,
  rejection_reason text,
  auto_transferred boolean DEFAULT false NOT NULL,
  submitted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS login_history (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text,
  user_id text,
  username text,
  ip text,
  user_agent text,
  country text,
  success boolean DEFAULT false NOT NULL,
  reason text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS logistics_events (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  logistics_request_id text NOT NULL,
  event_type text NOT NULL,
  from_status text,
  to_status text,
  actor_id text,
  actor_role text DEFAULT 'system'::text NOT NULL,
  message text,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS logistics_requests (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  partner_id text NOT NULL,
  portal_access_id text,
  number text NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  mode text NOT NULL,
  container_type text,
  incoterm text,
  target_pickup_date date,
  target_delivery_date date,
  urgency text,
  origin_company text,
  origin_contact_name text,
  origin_contact_phone text,
  origin_contact_email text,
  origin_country text,
  origin_state text,
  origin_city text,
  origin_postal_code text,
  origin_address_line text,
  origin_port text,
  destination_company text,
  destination_contact_name text,
  destination_contact_phone text,
  destination_contact_email text,
  destination_country text,
  destination_state text,
  destination_city text,
  destination_postal_code text,
  destination_address_line text,
  destination_port text,
  total_weight_kg numeric,
  total_volume_cbm numeric,
  total_packages integer,
  cargo_description text,
  hs_codes text,
  is_hazardous boolean DEFAULT false,
  is_temperature_controlled boolean DEFAULT false,
  temperature_range text,
  insurance_required boolean DEFAULT false,
  cargo_value numeric,
  cargo_currency text DEFAULT 'USD'::text,
  special_instructions text,
  packing_list jsonb DEFAULT '[]'::jsonb,
  quoted_price numeric,
  quoted_currency text,
  quoted_transit_days integer,
  quoted_notes text,
  linked_offer_id text,
  admin_notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  tracking_number text,
  tracking_url text,
  carrier text,
  carrier_reference text,
  quoted_at timestamp with time zone,
  accepted_at timestamp with time zone,
  shipped_at timestamp with time zone,
  delivered_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS mail_queue (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text,
  to_email text NOT NULL,
  subject text NOT NULL,
  body text DEFAULT ''::text NOT NULL,
  status text DEFAULT 'queued'::text NOT NULL,
  attempts integer DEFAULT 0 NOT NULL,
  error text,
  sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS meeting_notes (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  user_id text NOT NULL,
  title text NOT NULL,
  meeting_date timestamp with time zone,
  participants text,
  agenda text,
  notes text,
  action_items text,
  partner_id text,
  deal_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS module_groups (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  code text NOT NULL,
  name text NOT NULL,
  description text,
  icon text,
  color text,
  modules text DEFAULT '[]'::text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS notifications (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  user_id text,
  type text NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  entity_type text,
  entity_id text,
  read boolean DEFAULT false NOT NULL,
  read_at timestamp with time zone,
  action_url text,
  action_label text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  partner_id text
);

CREATE TABLE IF NOT EXISTS offers (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  number text NOT NULL,
  deal_id text,
  partner_id text NOT NULL,
  owner_id text,
  status text DEFAULT 'draft'::text NOT NULL,
  subject text NOT NULL,
  currency text DEFAULT 'USD'::text NOT NULL,
  subtotal numeric DEFAULT 0 NOT NULL,
  discount_total numeric DEFAULT 0 NOT NULL,
  tax_total numeric DEFAULT 0 NOT NULL,
  total numeric DEFAULT 0 NOT NULL,
  notes text,
  terms text,
  valid_until date,
  sent_at timestamp with time zone,
  responded_at timestamp with time zone,
  items jsonb DEFAULT '[]'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  offer_no text,
  bank_details text,
  pol text,
  pod text,
  vessel text,
  container_no text,
  lead_time text,
  packaging text,
  payment_terms text,
  tax_clause text,
  document_id text,
  pdf_file_url text,
  pdf_generated_at timestamp with time zone,
  selling_price numeric,
  quantity numeric,
  unit text,
  product_id text,
  incoterm text,
  services jsonb,
  payment_bank_idx integer,
  client_accepted_at timestamp with time zone,
  client_signature jsonb,
  client_note text,
  admin_reviewed_by_client boolean DEFAULT false,
  old_id text,
  deleted_at timestamp with time zone,
  pol_country text,
  pod_country text,
  delivery_address text,
  delivery_city text,
  delivery_country text,
  specification text,
  origin_country text,
  exchange_rate double precision,
  exchange_rate_date text,
  exchange_rate_note text,
  viewed_at timestamp with time zone,
  viewed_by_email text,
  view_count integer DEFAULT 0,
  version integer DEFAULT 1
);

CREATE TABLE IF NOT EXISTS partner_connections (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  source_id text NOT NULL,
  target_id text NOT NULL,
  relation_type text,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS partners (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  name text NOT NULL,
  entity_type text DEFAULT 'company'::text NOT NULL,
  type text DEFAULT 'buyer'::text NOT NULL,
  email text,
  phone text,
  website text,
  tax_id text,
  vat_number text,
  registration_number text,
  address_line text,
  city text,
  state text,
  postal_code text,
  country text,
  contact_name text,
  contact_email text,
  contact_phone text,
  bank_name text,
  bank_account text,
  bank_swift text,
  bank_iban text,
  preferred_currency text,
  preferred_incoterm text,
  preferred_payment_terms text,
  status text DEFAULT 'active'::text NOT NULL,
  risk_score integer DEFAULT 0 NOT NULL,
  notes text,
  tags ARRAY,
  portal_enabled boolean DEFAULT false NOT NULL,
  portal_token text,
  portal_level text DEFAULT 'none'::text NOT NULL,
  kyc_status text DEFAULT 'not_submitted'::text NOT NULL,
  kyc_data jsonb,
  kyc_reviewed_by text,
  kyc_reviewed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  is_commissioner boolean DEFAULT false NOT NULL,
  whatsapp text,
  lead_source text,
  rating integer DEFAULT 0 NOT NULL,
  portal_visible_products ARRAY,
  portal_permissions ARRAY,
  linked_company_id text,
  industry text,
  social jsonb,
  activities jsonb,
  old_id text
);

CREATE TABLE IF NOT EXISTS password_resets (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  target_type text NOT NULL,
  target_id text NOT NULL,
  tenant_id text,
  token_hash text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  used_at timestamp with time zone,
  requested_ip text,
  requested_ua text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS plan_upgrade_requests (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  requested_by text,
  requested_plan text NOT NULL,
  current_plan text,
  message text,
  status text DEFAULT 'pending'::text NOT NULL,
  reviewed_by text,
  reviewed_at timestamp with time zone,
  admin_note text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS plans (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  name text NOT NULL,
  description text,
  price_monthly double precision DEFAULT 0,
  price_yearly double precision DEFAULT 0,
  currency text DEFAULT 'EUR'::text,
  max_users integer DEFAULT 5,
  max_partners integer DEFAULT 0,
  max_monthly_documents integer DEFAULT 0,
  max_products integer DEFAULT 0,
  storage_mb integer DEFAULT 500,
  trial_days integer DEFAULT 15,
  included_modules text DEFAULT '[]'::text,
  custom_branding boolean DEFAULT false,
  api_access boolean DEFAULT false,
  priority_support boolean DEFAULT false,
  white_label boolean DEFAULT false,
  is_active boolean DEFAULT true,
  is_public boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS portal_access (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  partner_id text NOT NULL,
  tenant_id text NOT NULL,
  tier text DEFAULT 'standard'::text NOT NULL,
  can_view_offers boolean DEFAULT true NOT NULL,
  can_view_documents boolean DEFAULT true NOT NULL,
  can_view_catalog boolean DEFAULT true NOT NULL,
  can_view_invoices boolean DEFAULT false NOT NULL,
  can_view_profile boolean DEFAULT true NOT NULL,
  can_view_company_info boolean DEFAULT true NOT NULL,
  can_submit_rfq boolean DEFAULT true NOT NULL,
  can_download_pdf boolean DEFAULT true NOT NULL,
  exempt_kyc boolean DEFAULT false NOT NULL,
  exempt_document_upload boolean DEFAULT false NOT NULL,
  exempt_location_share boolean DEFAULT false NOT NULL,
  status text DEFAULT 'pending_approval'::text NOT NULL,
  approved_by text,
  approved_at timestamp with time zone,
  invited_at timestamp with time zone,
  welcome_email_sent boolean DEFAULT false NOT NULL,
  portal_email text,
  password_hash text,
  must_set_password boolean DEFAULT true NOT NULL,
  last_login_at timestamp with time zone,
  last_login_ip text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  failed_attempts integer DEFAULT 0 NOT NULL,
  locked_until timestamp with time zone,
  token_version integer DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS portal_messages (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  partner_id text NOT NULL,
  portal_access_id text,
  direction text NOT NULL,
  body text NOT NULL,
  sender_username text NOT NULL,
  sender_user_id text,
  read_at timestamp with time zone,
  delivered_email_at timestamp with time zone,
  attachment_url text,
  attachment_name text,
  attachment_type text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS portal_rfqs (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  partner_id text NOT NULL,
  portal_access_id text,
  number text NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  product_name text NOT NULL,
  product_description text,
  category text,
  quantity numeric DEFAULT 0 NOT NULL,
  unit text DEFAULT 'MT'::text NOT NULL,
  target_price numeric,
  currency text DEFAULT 'USD'::text NOT NULL,
  delivery_country text,
  delivery_port text,
  delivery_date date,
  incoterm text,
  specifications text,
  notes text,
  linked_offer_id text,
  linked_demand_id text,
  admin_notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  deal_id text,
  target_market text,
  end_use text,
  payment_method text,
  payment_terms text,
  delivery_schedule text,
  per_shipment_qty numeric,
  shipments_per_period integer,
  contract_duration_months integer,
  buyer_type text,
  third_party_company_name text,
  third_party_business_type text,
  third_party_country text,
  third_party_contact_email text,
  third_party_contact_phone text,
  third_party_tax_id text,
  third_party_website text,
  urgency text,
  packaging_requirements text,
  certifications_required text,
  quality_standard text,
  product_id text,
  source text
);

CREATE TABLE IF NOT EXISTS portal_uploads (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  partner_id text NOT NULL,
  portal_access_id text,
  category text DEFAULT 'general'::text NOT NULL,
  doc_type text,
  kyc_submission_id text,
  message_id text,
  filename text NOT NULL,
  storage_bucket text DEFAULT 'portal-uploads'::text NOT NULL,
  storage_path text NOT NULL,
  mime_type text NOT NULL,
  size_bytes bigint NOT NULL,
  uploaded_by_email text,
  description text,
  uploaded_at timestamp with time zone DEFAULT now() NOT NULL,
  deleted_at timestamp with time zone,
  deleted_by text
);

CREATE TABLE IF NOT EXISTS product_catalog (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  name text NOT NULL,
  category text DEFAULT 'OTHER'::text NOT NULL,
  hs_code text,
  description text,
  base_unit text DEFAULT 'MT'::text NOT NULL,
  specifications jsonb,
  origin_country text,
  images ARRAY,
  active boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  old_id text,
  brand text,
  shelf_life text,
  image_url text,
  logistics jsonb,
  coa_params jsonb,
  detailed_spec text,
  tags ARRAY,
  inventory jsonb,
  sku text
);

CREATE TABLE IF NOT EXISTS products (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  sku text NOT NULL,
  name text NOT NULL,
  description text,
  category text,
  unit text DEFAULT 'pcs'::text NOT NULL,
  price numeric DEFAULT 0 NOT NULL,
  currency text DEFAULT 'USD'::text NOT NULL,
  cost numeric,
  stock numeric DEFAULT 0 NOT NULL,
  reorder_level numeric DEFAULT 0 NOT NULL,
  active boolean DEFAULT true NOT NULL,
  attributes jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  hs_code text,
  brand text,
  shelf_life text,
  image_url text,
  logistics jsonb,
  coa_params jsonb,
  detailed_spec text,
  tags ARRAY,
  old_id text,
  inventory jsonb,
  show_in_catalog boolean DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS proformas (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  number text NOT NULL,
  offer_id text,
  partner_id text NOT NULL,
  status text DEFAULT 'draft'::text NOT NULL,
  subject text NOT NULL,
  currency text DEFAULT 'USD'::text NOT NULL,
  subtotal numeric DEFAULT 0 NOT NULL,
  discount_total numeric DEFAULT 0 NOT NULL,
  tax_total numeric DEFAULT 0 NOT NULL,
  total numeric DEFAULT 0 NOT NULL,
  issue_date date DEFAULT CURRENT_DATE NOT NULL,
  valid_until date DEFAULT (CURRENT_DATE + 14) NOT NULL,
  sent_at timestamp with time zone,
  paid_at timestamp with time zone,
  notes text,
  items jsonb DEFAULT '[]'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  payment_terms text,
  deleted_at timestamp with time zone,
  incoterm text,
  pol text,
  pol_country text,
  pod text,
  pod_country text,
  vessel text,
  container_no text,
  lead_time text,
  packaging text,
  delivery_address text,
  delivery_city text,
  delivery_country text,
  specification text,
  origin_country text,
  exchange_rate double precision,
  exchange_rate_date text,
  exchange_rate_note text,
  viewed_at timestamp with time zone,
  viewed_by_email text,
  view_count integer DEFAULT 0,
  version integer DEFAULT 1
);

CREATE TABLE IF NOT EXISTS project_tasks (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  user_id text,
  deal_id text,
  title text NOT NULL,
  description text,
  status text DEFAULT 'todo'::text,
  priority text DEFAULT 'normal'::text,
  assigned_to text,
  due_date date,
  estimated_hours double precision,
  actual_hours double precision DEFAULT 0,
  tags text,
  position integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS quick_notes (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  user_id text NOT NULL,
  title text DEFAULT ''::text,
  content text DEFAULT ''::text,
  category text DEFAULT 'general'::text,
  color text DEFAULT '#f59e0b'::text,
  pinned boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS recurring_expenses (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  account_id text NOT NULL,
  description text NOT NULL,
  category text,
  amount double precision DEFAULT 0 NOT NULL,
  currency text DEFAULT 'USD'::text NOT NULL,
  day_of_month integer DEFAULT 1 NOT NULL,
  start_date date,
  last_applied date,
  is_active boolean DEFAULT true NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS reminders (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  user_id text NOT NULL,
  title text NOT NULL,
  description text,
  due_at timestamp with time zone,
  priority text DEFAULT 'normal'::text,
  entity_type text,
  entity_id text,
  completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  snoozed_until timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sessions (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  user_id text NOT NULL,
  token text,
  ip text,
  user_agent text,
  country text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  last_used_at timestamp with time zone,
  expires_at timestamp with time zone NOT NULL,
  revoked boolean DEFAULT false NOT NULL,
  current boolean DEFAULT false NOT NULL,
  tenant_id text NOT NULL
);

CREATE TABLE IF NOT EXISTS settings (
  key text NOT NULL,
  tenant_id text,
  value jsonb,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  id text DEFAULT (gen_random_uuid())::text NOT NULL
);

CREATE TABLE IF NOT EXISTS shared_documents (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  partner_id text NOT NULL,
  filename text NOT NULL,
  mime_type text DEFAULT 'application/octet-stream'::text NOT NULL,
  size bigint DEFAULT 0 NOT NULL,
  storage_path text NOT NULL,
  category text DEFAULT 'other'::text NOT NULL,
  uploaded_by text,
  visible_to_partner boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS supplier_offers (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  product_id text NOT NULL,
  supplier_id text NOT NULL,
  offer_number text,
  status text DEFAULT 'active'::text NOT NULL,
  unit_price numeric DEFAULT 0 NOT NULL,
  currency text DEFAULT 'USD'::text NOT NULL,
  min_order_qty numeric,
  price_valid_until date,
  packaging text,
  packing_details text,
  loadability text,
  specification_notes text,
  origin_country text,
  incoterm text DEFAULT 'FOB'::text NOT NULL,
  loading_port text,
  delivery_port text,
  lead_time_days integer,
  payment_terms text,
  inspection text,
  certificate text,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS team_chat_messages (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  sender_id text NOT NULL,
  channel text DEFAULT 'general'::text,
  message text NOT NULL,
  reply_to text,
  attachments text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tenant_letterheads (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  name text NOT NULL,
  is_default boolean DEFAULT false,
  company_name text,
  company_legal_name text,
  company_address_line text,
  company_city text,
  company_postal_code text,
  company_country text,
  company_email text,
  company_phone text,
  company_website text,
  company_vat_number text,
  company_tax_id text,
  company_registration_number text,
  bank_name text,
  bank_iban text,
  bank_swift text,
  bank_account_holder text,
  logo_url text,
  logo_position text DEFAULT 'left'::text,
  logo_width_mm integer DEFAULT 40,
  logo_height_mm integer DEFAULT 15,
  logo_lock_aspect boolean DEFAULT true,
  primary_color text DEFAULT '#0f766e'::text,
  accent_color text DEFAULT '#0d9488'::text,
  text_color text DEFAULT '#0f172a'::text,
  muted_text_color text DEFAULT '#64748b'::text,
  page_size text DEFAULT 'A4'::text,
  margin_top_mm integer DEFAULT 25,
  margin_bottom_mm integer DEFAULT 25,
  margin_left_mm integer DEFAULT 20,
  margin_right_mm integer DEFAULT 20,
  header_height_mm integer DEFAULT 35,
  footer_height_mm integer DEFAULT 28,
  header_layout text DEFAULT 'logo-left-info-right'::text,
  header_show_logo boolean DEFAULT true,
  header_show_company_name boolean DEFAULT true,
  header_show_contact boolean DEFAULT true,
  header_show_vat boolean DEFAULT false,
  header_divider boolean DEFAULT true,
  header_divider_color text DEFAULT '#e2e8f0'::text,
  header_custom_html text,
  footer_layout text DEFAULT 'bank-contact-tax'::text,
  footer_show_bank_details boolean DEFAULT true,
  footer_show_contact boolean DEFAULT true,
  footer_show_tax_id boolean DEFAULT true,
  footer_show_page_number boolean DEFAULT true,
  footer_divider boolean DEFAULT true,
  footer_divider_color text DEFAULT '#e2e8f0'::text,
  footer_custom_html text,
  footer_text text,
  watermark_enabled boolean DEFAULT false,
  watermark_text text,
  watermark_color text DEFAULT '#94a3b8'::text,
  watermark_opacity double precision DEFAULT 0.08,
  watermark_rotation double precision DEFAULT '-45'::integer,
  body_font_family text DEFAULT 'Inter, system-ui, sans-serif'::text,
  body_font_size_pt integer DEFAULT 11,
  heading_font_family text DEFAULT 'Inter, system-ui, sans-serif'::text,
  heading_font_size_pt integer DEFAULT 16,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tenant_seals (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  name text NOT NULL,
  is_default boolean DEFAULT false,
  image_url text NOT NULL,
  image_width_mm integer DEFAULT 35,
  image_height_mm integer DEFAULT 35,
  image_format text DEFAULT 'png'::text,
  position text DEFAULT 'bottom-right'::text,
  offset_x_mm integer DEFAULT 0,
  offset_y_mm integer DEFAULT 0,
  opacity double precision DEFAULT 1.0,
  rotation_deg double precision DEFAULT 0,
  apply_to_types text DEFAULT '[]'::text,
  signature_enabled boolean DEFAULT false,
  signature_label text,
  signature_name text,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tenants (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  name text NOT NULL,
  legal_name text,
  country text,
  currency text DEFAULT 'USD'::text NOT NULL,
  tax_id text,
  vat_number text,
  registration_number text,
  address_line text,
  city text,
  postal_code text,
  bank_name text,
  bank_iban text,
  bank_swift text,
  logo_url text,
  primary_color text,
  plan text DEFAULT 'trial'::text NOT NULL,
  status text DEFAULT 'active'::text NOT NULL,
  max_users integer DEFAULT 10 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  website text,
  phone text,
  email text,
  bank_accounts jsonb,
  subscription_start timestamp with time zone,
  subscription_end timestamp with time zone,
  trial_ends_at timestamp with time zone,
  billing_cycle text DEFAULT 'monthly'::text,
  amount_paid double precision DEFAULT 0,
  currency_paid text DEFAULT 'EUR'::text,
  trial_days integer DEFAULT 10 NOT NULL
);

CREATE TABLE IF NOT EXISTS time_entries (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  user_id text NOT NULL,
  partner_id text,
  deal_id text,
  description text NOT NULL,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone,
  duration_minutes integer,
  billable boolean DEFAULT false,
  hourly_rate double precision,
  currency text DEFAULT 'EUR'::text,
  status text DEFAULT 'open'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS trade_calculations (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  name text NOT NULL,
  product_id text,
  supplier_offer_id text,
  supplier_id text,
  buyer_id text,
  quantity numeric DEFAULT 0 NOT NULL,
  unit text DEFAULT 'MT'::text NOT NULL,
  num_containers integer DEFAULT 1 NOT NULL,
  container_type text,
  buy_price_per_unit numeric DEFAULT 0 NOT NULL,
  buy_currency text DEFAULT 'USD'::text NOT NULL,
  buy_incoterm text DEFAULT 'FOB'::text NOT NULL,
  sell_price_per_unit numeric DEFAULT 0 NOT NULL,
  sell_currency text DEFAULT 'USD'::text NOT NULL,
  sell_incoterm text DEFAULT 'CIF'::text NOT NULL,
  transport_mode text DEFAULT 'SEA'::text NOT NULL,
  loading_port text,
  delivery_port text,
  exchange_rate numeric DEFAULT 1 NOT NULL,
  cost_lines jsonb DEFAULT '[]'::jsonb NOT NULL,
  total_buy_cost numeric DEFAULT 0 NOT NULL,
  total_landed_cost numeric DEFAULT 0 NOT NULL,
  total_sell_revenue numeric DEFAULT 0 NOT NULL,
  gross_margin numeric DEFAULT 0 NOT NULL,
  margin_percent numeric DEFAULT 0 NOT NULL,
  created_by text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS trusted_devices (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  user_id text NOT NULL,
  device_name text NOT NULL,
  fingerprint text NOT NULL,
  ip text,
  last_used timestamp with time zone DEFAULT now() NOT NULL,
  revoked boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  tenant_id text NOT NULL
);

CREATE TABLE IF NOT EXISTS user_preferences (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  user_id text NOT NULL,
  preference_key text NOT NULL,
  preference_value text NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS user_tasks (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  user_id text NOT NULL,
  title text NOT NULL,
  done boolean DEFAULT false NOT NULL,
  due_date date,
  entity_type text,
  entity_id text,
  priority text DEFAULT 'medium'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text,
  username text NOT NULL,
  email text NOT NULL,
  full_name text,
  role text DEFAULT 'staff'::text NOT NULL,
  permissions jsonb,
  password_hash text NOT NULL,
  totp_secret text,
  totp_enabled boolean DEFAULT false NOT NULL,
  locked_until timestamp with time zone,
  failed_attempts integer DEFAULT 0 NOT NULL,
  last_login_at timestamp with time zone,
  last_login_ip text,
  last_login_country text,
  must_change_password boolean DEFAULT false NOT NULL,
  token_version integer DEFAULT 1 NOT NULL,
  signature text,
  notif_prefs jsonb,
  active boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS vault_secrets (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  key text NOT NULL,
  description text,
  encrypted_value text NOT NULL,
  category text DEFAULT 'other'::text NOT NULL,
  last_accessed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS verification_logs (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  verification_id text NOT NULL,
  code text NOT NULL,
  ip text,
  user_agent text,
  result text NOT NULL,
  details jsonb,
  verified_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS webhooks (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  tenant_id text NOT NULL,
  name text NOT NULL,
  url text NOT NULL,
  events jsonb DEFAULT '[]'::jsonb NOT NULL,
  secret text NOT NULL,
  last_triggered_at timestamp with time zone,
  last_status integer,
  active boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

